# Generated by Django 4.1 on 2022-09-04 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Путь к фотографии')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('photo', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Путь к фотографии')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='train_main_app.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Станция',
                'verbose_name_plural': 'Станции',
                'db_table': 'stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('wagons_number', models.SmallIntegerField(default=0, verbose_name='Количество вагонов')),
                ('bc_wagons_numbers', models.CharField(default=0, max_length=255, verbose_name='Номера вагонов бизнес-класса')),
                ('seats_in_row', models.SmallIntegerField(default=0, verbose_name='Мест в ряду')),
                ('rows_number', models.SmallIntegerField(default=0, verbose_name='Количество рядов в вагоне')),
                ('total_seats', models.SmallIntegerField(default=0, verbose_name='Всего мест')),
                ('seats_naming_type', models.CharField(choices=[('INCR', 'Incrementing')], default='INCR', max_length=4)),
            ],
            options={
                'verbose_name': 'Поезд',
                'verbose_name_plural': 'Поезда',
                'db_table': 'trains',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('departure_datetime', models.DateTimeField(verbose_name='Время отправления')),
                ('price_per_station', models.IntegerField(blank=True, default=0, verbose_name='Цена за один переезд (станцию)')),
                ('bc_price_per_station', models.IntegerField(blank=True, default=0, verbose_name='Цена за один переезд (станцию) для бизнес-класса')),
                ('taken_seats', models.CharField(blank=True, max_length=2048, verbose_name='Занятые места')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_city', to='train_main_app.city', verbose_name='Город прибытия')),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_station', to='train_main_app.station', verbose_name='Станция прибытия')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_city', to='train_main_app.city', verbose_name='Город отправления')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_station', to='train_main_app.station', verbose_name='Станция отправления')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='train_main_app.train', verbose_name='Поезд')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'db_table': 'voyages',
                'ordering': ['departure_datetime'],
            },
        ),
        migrations.CreateModel(
            name='StationInVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_datetime', models.DateTimeField(verbose_name='Время прибытия')),
                ('station_order', models.PositiveIntegerField(default=0, verbose_name='Порядок следования')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_main_app.station', verbose_name='Станция')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_main_app.voyage', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Станция в маршруте',
                'verbose_name_plural': 'Станции в маршрутах',
                'db_table': 'stations_in_voyage',
            },
        ),
        migrations.CreateModel(
            name='PurchasedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers_phone_number', models.CharField(max_length=50, verbose_name='Телефон клиента')),
                ('customers_country_code', models.CharField(default=None, max_length=5, verbose_name='Код страны')),
                ('purchase_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время покупки')),
                ('seat_number', models.CharField(max_length=50, verbose_name='Место')),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_st', to='train_main_app.stationinvoyage', verbose_name='Станция прибытия')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_st', to='train_main_app.stationinvoyage', verbose_name='Станция отправления')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='train_main_app.voyage', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Купленный билет',
                'verbose_name_plural': 'Купленные билеты',
                'db_table': 'purchased_tickets',
                'ordering': ['purchase_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default=None, max_length=5, verbose_name='Код страны')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'customers',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='train_main_app.country', verbose_name='Страна'),
        ),
    ]
