# Generated by Django 4.1 on 2022-09-05 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedticket',
            old_name='customers_country_code',
            new_name='customers_region_code',
        ),
    ]
