# Generated by Django 4.1 on 2022-11-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_main_app', '0005_alter_purchasedticket_customers_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyage',
            old_name='title',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='PurchasedTicket',
        ),
    ]
