# Generated by Django 4.1.3 on 2022-11-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedticket',
            name='pdf_filename',
            field=models.CharField(default='', max_length=50, verbose_name='PDF file'),
            preserve_default=False,
        ),
    ]
