# Generated by Django 4.1.3 on 2022-11-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_purchasedticket_pdf_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='pdf_filename',
            field=models.CharField(max_length=50, null=True, verbose_name='PDF file'),
        ),
    ]
